import nx from '@nx/eslint-plugin';

export default [
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],
  {
    ignores: ['**/dist', '**/out-tsc'],
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: ['^.*/eslint(\\.base)?\\.config\\.[cm]?[jt]s$'],
          depConstraints: [
            // scope: no module may import another module's internals.
            // Cross-module data flows through shared/types contracts, not direct imports.
            { sourceTag: 'scope:shared', onlyDependOnLibsWithTags: ['scope:shared'] },
            { sourceTag: 'scope:invoicing', onlyDependOnLibsWithTags: ['scope:invoicing', 'scope:shared'] },
            { sourceTag: 'scope:companies', onlyDependOnLibsWithTags: ['scope:companies', 'scope:shared'] },
            { sourceTag: 'scope:quotes', onlyDependOnLibsWithTags: ['scope:quotes', 'scope:shared'] },
            { sourceTag: 'scope:receivables', onlyDependOnLibsWithTags: ['scope:receivables', 'scope:shared'] },
            { sourceTag: 'scope:inventory', onlyDependOnLibsWithTags: ['scope:inventory', 'scope:shared'] },
            { sourceTag: 'scope:inventory-cart', onlyDependOnLibsWithTags: ['scope:inventory-cart', 'scope:shared'] },
            { sourceTag: 'scope:taxes', onlyDependOnLibsWithTags: ['scope:taxes', 'scope:shared'] },
            { sourceTag: 'scope:accounting', onlyDependOnLibsWithTags: ['scope:accounting', 'scope:shared'] },
            { sourceTag: 'scope:reports-pnl', onlyDependOnLibsWithTags: ['scope:reports-pnl', 'scope:shared'] },
            { sourceTag: 'scope:reports-sales', onlyDependOnLibsWithTags: ['scope:reports-sales', 'scope:shared'] },
            { sourceTag: 'scope:reports-financial', onlyDependOnLibsWithTags: ['scope:reports-financial', 'scope:shared'] },
            { sourceTag: 'scope:tenant-settings', onlyDependOnLibsWithTags: ['scope:tenant-settings', 'scope:shared'] },
            { sourceTag: 'scope:activity-log', onlyDependOnLibsWithTags: ['scope:activity-log', 'scope:shared'] },
            { sourceTag: 'scope:purchases', onlyDependOnLibsWithTags: ['scope:purchases', 'scope:shared'] },
            { sourceTag: 'scope:payables', onlyDependOnLibsWithTags: ['scope:payables', 'scope:shared'] },
            { sourceTag: 'scope:treasury', onlyDependOnLibsWithTags: ['scope:treasury', 'scope:shared'] },
            { sourceTag: 'scope:mercadopago', onlyDependOnLibsWithTags: ['scope:mercadopago', 'scope:shared'] },
            {
              sourceTag: 'scope:api',
              onlyDependOnLibsWithTags: [
                'scope:shared',
                'scope:invoicing',
                'scope:companies',
                'scope:quotes',
                'scope:receivables',
                'scope:inventory',
                'scope:inventory-cart',
                'scope:taxes',
                'scope:accounting',
                'scope:reports-pnl',
                'scope:reports-sales',
                'scope:reports-financial',
                'scope:tenant-settings',
                'scope:activity-log',
                'scope:purchases',
                'scope:payables',
                'scope:treasury',
                'scope:mercadopago',
                'scope:bank-reconciliation',
                'scope:pos',
              ],
            },
            {
              sourceTag: 'scope:web',
              onlyDependOnLibsWithTags: [
                'scope:shared',
                'scope:invoicing',
                'scope:companies',
                'scope:quotes',
                'scope:receivables',
                'scope:inventory',
                'scope:inventory-cart',
                'scope:taxes',
                'scope:accounting',
                'scope:reports-pnl',
                'scope:reports-sales',
                'scope:reports-financial',
                'scope:tenant-settings',
                'scope:activity-log',
                'scope:purchases',
                'scope:payables',
                'scope:treasury',
              ],
            },
            // type: layering. apps/features can use anything below them,
            // data-access/ui/util can't reach back up into feature or app code.
            { sourceTag: 'type:app', onlyDependOnLibsWithTags: ['type:feature', 'type:ui', 'type:data-access', 'type:util'] },
            { sourceTag: 'type:feature', onlyDependOnLibsWithTags: ['type:feature', 'type:ui', 'type:data-access', 'type:util'] },
            { sourceTag: 'type:data-access', onlyDependOnLibsWithTags: ['type:data-access', 'type:util'] },
            { sourceTag: 'type:ui', onlyDependOnLibsWithTags: ['type:ui', 'type:util'] },
            { sourceTag: 'type:util', onlyDependOnLibsWithTags: ['type:util'] },
          ],
        },
      ],
    },
  },
  {
    files: [
      '**/*.ts',
      '**/*.tsx',
      '**/*.cts',
      '**/*.mts',
      '**/*.js',
      '**/*.jsx',
      '**/*.cjs',
      '**/*.mjs',
    ],
    // Override or add rules here
    rules: {},
  },
];
