export * from './lib/taxes.module.js';
export * from './lib/taxes.service.js';
export * from './lib/withholding-regime.service.js';
export * from './lib/tax-deadline.service.js';
export * from './lib/dto/create-tax-definition.dto.js';
export * from './lib/dto/revise-tax-definition.dto.js';
export * from './lib/dto/create-withholding-regime.dto.js';
export * from './lib/dto/revise-withholding-regime.dto.js';
export * from './lib/dto/create-tax-deadline.dto.js';
